# Generated by Django 5.1.1 on 2024-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team08_09',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=255)),
                ('ppg', models.FloatField()),
            ],
        ),
    ]
